import jsPDF from "jspdf";

export function downloadEcoReport(companyName, industry, result) {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(16, 185, 129);
  doc.text("GREENCHAIN", 20, 20);
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`ESG Audit Report - Confidential`, 20, 30);
  
  // Divider line
  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(0.5);
  doc.line(20, 35, 190, 35);
  
  // Company details
  doc.setTextColor(50, 50, 50);
  doc.text(`Company: ${companyName}`, 20, 45);
  doc.text(`Industry: ${industry}`, 20, 52);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 59);
  
  // Score section
  doc.setFontSize(16);
  doc.setTextColor(16, 185, 129);
  doc.text(`Eco-Score: ${result.score}/100`, 20, 75);
  
  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  doc.text(`Risk Level: ${result.riskLevel}`, 20, 85);
  doc.text(`CO2 Savings Potential: ${result.co2}`, 20, 92);
  doc.text(`Estimated Savings: ${result.money}`, 20, 99);
  
  // Key Findings
  doc.setFontSize(13);
  doc.setTextColor(16, 185, 129);
  doc.text("Key Findings:", 20, 115);
  
  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  result.factors.forEach((f, i) => {
    doc.text(`• ${f}`, 22, 125 + i * 8);
  });
  
  // Recommendation
  doc.setFontSize(13);
  doc.setTextColor(16, 185, 129);
  doc.text("Recommendation:", 20, 155);
  
  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  doc.text(result.improvement, 22, 163);
  
  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("Powered by Gemini 1.5 Flash + IBM Granite Prompt", 20, 185);
  doc.text("Generated by GREENCHAIN Platform", 20, 192);
  
  doc.save(`${companyName}_Eco_Report.pdf`);
}
